### ISSUE TITLE
当阅读的时候出现error

### ISSUE THREAD

**Issue by littleKun** [lidong1665/AndroidPDF#2]
java.lang.RuntimeException: An error occured while executing doInBackground()
                                                       at android.os.AsyncTask$3.done(AsyncTask.java:299)
                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:239)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                       at java.lang.Thread.run(Thread.java:856)
                                                    Caused by: java.lang.RuntimeException: error loading page
                                                       at org.vudroid.pdfdroid.codec.PdfPage.open(Native Method)
                                                       at org.vudroid.pdfdroid.codec.PdfPage.createPage(PdfPage.java:55)
                                                       at org.vudroid.pdfdroid.codec.PdfDocument.getPage(PdfDocument.java:18)
                                                       at org.vudroid.core.DecodeServiceBase.getPage(DecodeServiceBase.java:175)
                                                       at com.lidong.pdf.RenderingAsyncTask.proceed(RenderingAsyncTask.java:101)
                                                       at com.lidong.pdf.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:64)
                                                       at com.lidong.pdf.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:34)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:287)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
                                                       at java.lang.Thread.run(Thread.java:856) 

当滑动到第四页即出现这个异常

**Comment by lidong1665** [comment]
直接传网络pdf的地址。

**Comment by qhzzl** [comment]
同样的问题，加载第一页就闪退的，而有的却不会闪退，没有问题，不知道问什么？

**Comment by gexiangjie** [comment]
我是第一页就出现了这个问题

**Comment by pechpijit** [comment]
allow permission:
     <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

**Comment by gexiangjie** [comment]
都加过了 没有什么作用
