### ISSUE TITLE
加载异常

### ISSUE THREAD

**Issue by cy000** [lidong1665/AndroidPDF#3]
03-09 10:21:01.299 12188-12188/com.yourong.zhongchou E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.yourong.zhongchou, PID: 12188
                                                                       java.lang.RuntimeException: error loading page
                                                                           at org.vudroid.pdfdroid.codec.PdfPage.open(Native Method)
                                                                           at org.vudroid.pdfdroid.codec.PdfPage.createPage(PdfPage.java:55)
                                                                           at org.vudroid.pdfdroid.codec.PdfDocument.getPage(PdfDocument.java:18)
                                                                           at org.vudroid.core.DecodeServiceBase.getPage(DecodeServiceBase.java:175)
                                                                           at org.vudroid.core.DecodeServiceBase.getPageWidth(DecodeServiceBase.java:214)
                                                                           at com.lidong.pdf.PDFView.loadComplete(PDFView.java:646)
                                                                           at com.lidong.pdf.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:57)
                                                                           at com.lidong.pdf.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:30)
                                                                           at android.os.AsyncTask.finish(AsyncTask.java:632)
                                                                           at android.os.AsyncTask.access$600(AsyncTask.java:177)
                                                                           at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:136)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5054)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                           at dalvik.system.NativeStart.main(Native Method)

**Comment by lidong1665** [comment]
这是下载的文件错误。所以就会报错

**Comment by qhzzl** [comment]
不是吧！！！
