### ISSUE TITLE
出现如下错误怎么解决？

### ISSUE THREAD

**Issue by qhzzl** [lidong1665/AndroidPDF#6]
An error occurred while executing doInBackground()

**Comment by qhzzl** [comment]
java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                      at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                      at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                      at java.lang.Thread.run(Thread.java:818)
                                                                   Caused by: java.lang.RuntimeException: error loading page
                                                                      at org.vudroid.pdfdroid.codec.PdfPage.open(Native Method)
                                                                      at org.vudroid.pdfdroid.codec.PdfPage.createPage(PdfPage.java:55)
                                                                      at org.vudroid.pdfdroid.codec.PdfDocument.getPage(PdfDocument.java:18)
                                                                      at org.vudroid.core.DecodeServiceBase.getPage(DecodeServiceBase.java:175)
                                                                      at com.lidong.pdf.RenderingAsyncTask.proceed(RenderingAsyncTask.java:101)
                                                                      at com.lidong.pdf.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:64)
                                                                      at com.lidong.pdf.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:34)
                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
