### ISSUE TITLE
换了好几个URL  都是这样的错误，求解。大神

### ISSUE THREAD

**Issue by KomoriWu** [lidong1665/AndroidPDF#8]
Process: com.txtled.ellia, PID: 2045
                                                                java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                    at android.os.AsyncTask$3.done(AsyncTask.java:325)
                                                                    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                    at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                    at java.lang.Thread.run(Thread.java:761)
                                                                 Caused by: java.lang.RuntimeException: PDF file is corrupted
                                                                    at org.vudroid.pdfdroid.codec.PdfDocument.open(Native Method)
                                                                    at org.vudroid.pdfdroid.codec.PdfDocument.openDocument(PdfDocument.java:28)
                                                                    at org.vudroid.pdfdroid.codec.PdfContext.openDocument(PdfContext.java:18)
                                                                    at org.vudroid.core.DecodeServiceBase.open(DecodeServiceBase.java:59)
                                                                    at com.lidong.pdf.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:51)
                                                                    at com.lidong.pdf.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:30)
                                                                    at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                    at java.lang.Thread.run(Thread.java:761)

**Comment by gexiangjie** [comment]
我也报了这个错误
